version: '3'

services:
  sipe-backend-postgres:
    container_name: desafio-programacao-db
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_DB: desafio-programacao-db
      POSTGRES_USER: desafio-programacao
      POSTGRES_PASSWORD: desafio-programacao
    ports:
      - 5432:5432